---
- name: Verificar si AWS CLI ya esta instalado
  ansible.builtin.command: aws --version
  register: aws_cli_check
  changed_when: false
  failed_when: false

- name: Instalar AWS CLI v2
  when: aws_cli_check.rc != 0
  block:
    - name: Descargar el instalador de AWS CLI v2
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: "0644"

    - name: Descomprimir el instalador
      ansible.builtin.unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: true

    - name: Ejecutar el instalador de AWS CLI
      ansible.builtin.command: /tmp/aws/install
      changed_when: true

- name: Confirmar version de AWS CLI
  ansible.builtin.command: aws --version
  register: aws_cli_final
  changed_when: false

- name: Mostrar version de AWS CLI instalada
  ansible.builtin.debug:
    msg: "{{ aws_cli_final.stdout }}"
