---
- name: Actualizar cache de apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Instalar paquetes base
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - unzip
      - git
    state: present
